CREATE TABLE IF NOT EXISTS npc_core_npcs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  npc_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  model VARCHAR(128) NOT NULL DEFAULT 'mp_m_freemode_01',
  state VARCHAR(64) NOT NULL DEFAULT 'idle',
  job VARCHAR(64) NOT NULL DEFAULT 'civilian',
  district VARCHAR(64) NOT NULL DEFAULT 'downtown',
  x FLOAT NOT NULL DEFAULT 0,
  y FLOAT NOT NULL DEFAULT 0,
  z FLOAT NOT NULL DEFAULT 0,
  heading FLOAT NOT NULL DEFAULT 0,
  crime_level INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS npc_core_states (
  id INT AUTO_INCREMENT PRIMARY KEY,
  npc_id VARCHAR(64) NOT NULL,
  state VARCHAR(64) NOT NULL,
  activity VARCHAR(128) DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_npc_state (npc_id)
);

CREATE TABLE IF NOT EXISTS npc_core_memory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  npc_id VARCHAR(64) NOT NULL,
  memory_key VARCHAR(128) NOT NULL,
  memory_value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_npc_memory (npc_id, memory_key)
);
